# config

# Configuration for request-info - https://github.com/behaviorbot/request-info

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/PR!
requestInfoLabelToAdd: needs more info
checkIssueTemplate: true
checkPullRequestTemplate: true
requestInfoOn:
  pullRequest: true
  issue: true
