# stale.yml
# Configuration for probot-stale - https://github.com/probot/stale

daysUntilStale: 365
daysUntilClose: false
exemptLabels: []
exemptProjects: false
exemptMilestones: false
staleLabel: stale
markComment: false
closeComment: false
